clear; clc; close all;
cdir = pwd;
Datasets = {[cdir '/../Dataset/01-office/'], ...   
    [cdir '/../Dataset/02-teddy/'],...
    [cdir '/../Dataset/03-large-cabinet/'],...
    [cdir '/../Dataset/04-kitti/'],...
    [cdir '/../Dataset/05-castle/'],...
    [cdir '/../Dataset/06-office-wide/'], ...
    [cdir '/../Dataset/07-teddy-wide/'],...
    [cdir '/../Dataset/08-large-cabinet-wide/']};

ResultsDir = {[cdir '/../Results/01-office/'], ...   
    [cdir '/../Results/02-teddy/'],...
    [cdir '/../Results/03-large-cabinet/'],...
    [cdir '/../Results/04-kitti/'],...
    [cdir '/../Results/05-castle/'],...
    [cdir '/../Results/06-office-wide/'], ...
    [cdir '/../Results/07-teddy-wide/'],...
    [cdir '/../Results/08-large-cabinet-wide/']};

exe = [cdir '/bin/Release/gms_matcher '];

for d = 1 : length(Datasets)

    cmd1 = [exe  Datasets{d} ' ' ResultsDir{d} ' single-scale' ];
    system(cmd1);

	if(d > 4)
		cmd2 = [exe  Datasets{d} ' ' ResultsDir{d} ' multi-scale' ];
		system(cmd2);
	end
end
